import AppLayout from "@/components/AppLayout";
import { ReduxProvider } from "@/redux/ReduxProvider";
import { Toaster } from "react-hot-toast";

import { Inter } from "next/font/google";
import "./globals.css";

const inter=Inter({ subsets: ["latin"] });

export const metadata={
  title: "ArbroPreetpalAssignment",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <AppLayout>
            <Toaster position="top-center" />
            {children}
          </AppLayout>
        </ReduxProvider>
      </body>
    </html>
  );
}
